import type { ShaderGradient } from "@shadergradient/react";
import type { ComponentProps } from "react";

type GradientProps = ComponentProps<typeof ShaderGradient>;

/**
 * shadergradient.co presets for the Value Proposition phase cards, one per
 * phase (cycled if there are more phases than presets). Editor-only props
 * (axesHelper, destination, embedMode, format, frameRate, gizmoHelper,
 * pixelDensity, fov, bgColor*) are dropped; the canvas takes pixelDensity/fov.
 */
export const presets: GradientProps[] = [
  {
    type: "sphere",
    brightness: 1.5,
    cAzimuthAngle: 250,
    cDistance: 1.5,
    cPolarAngle: 140,
    cameraZoom: 12.5,
    color1: "#809bd6",
    color2: "#910aff",
    color3: "#af38ff",
    envPreset: "city",
    grain: "on",
    lightType: "3d",
    positionX: 0,
    positionY: 0,
    positionZ: 0,
    range: "disabled",
    rangeEnd: 40,
    rangeStart: 0,
    reflection: 0.5,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 140,
    shader: "defaults",
    uAmplitude: 7,
    uDensity: 0.8,
    uFrequency: 5.5,
    uSpeed: 0.3,
    uStrength: 0.4,
    uTime: 0,
    wireframe: false,
  },
  {
    type: "sphere",
    brightness: 1.5,
    cAzimuthAngle: 250,
    cDistance: 1.5,
    cPolarAngle: 140,
    cameraZoom: 12.5,
    color1: "#809bd6",
    color2: "#910aff",
    color3: "#af38ff",
    envPreset: "city",
    grain: "on",
    lightType: "3d",
    positionX: 0,
    positionY: 0,
    positionZ: 0,
    range: "disabled",
    rangeEnd: 40,
    rangeStart: 0,
    reflection: 0.5,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 140,
    shader: "defaults",
    uAmplitude: 7,
    uDensity: 0.8,
    uFrequency: 5.5,
    uSpeed: 0.3,
    uStrength: 0.4,
    uTime: 0,
    wireframe: false,
  },
  {
    type: "waterPlane",
    brightness: 1,
    cAzimuthAngle: 180,
    cDistance: 2.8,
    cPolarAngle: 80,
    cameraZoom: 9.1,
    color1: "#606080",
    color2: "#8d7dca",
    color3: "#212121",
    envPreset: "city",
    grain: "on",
    lightType: "3d",
    positionX: 0,
    positionY: 0,
    positionZ: 0,
    range: "disabled",
    rangeEnd: 40,
    rangeStart: 0,
    reflection: 0.1,
    rotationX: 50,
    rotationY: 0,
    rotationZ: -60,
    shader: "defaults",
    uAmplitude: 0,
    uDensity: 1.5,
    uFrequency: 0,
    uSpeed: 0.3,
    uStrength: 1.5,
    uTime: 8,
    wireframe: false,
  },
  {
    type: "waterPlane",
    brightness: 1.1,
    cAzimuthAngle: 180,
    cDistance: 3.9,
    cPolarAngle: 115,
    cameraZoom: 1,
    color1: "#5606ff",
    color2: "#fe8989",
    color3: "#000000",
    envPreset: "city",
    grain: "off",
    lightType: "3d",
    positionX: -0.5,
    positionY: 0.1,
    positionZ: 0,
    range: "disabled",
    rangeEnd: 40,
    rangeStart: 0,
    reflection: 0.1,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 235,
    shader: "defaults",
    uAmplitude: 0,
    uDensity: 1.1,
    uFrequency: 5.5,
    uSpeed: 0.1,
    uStrength: 2.4,
    uTime: 0.2,
    wireframe: false,
  },
  {
    type: "plane",
    brightness: 1.2,
    cAzimuthAngle: 180,
    cDistance: 3.6,
    cPolarAngle: 90,
    cameraZoom: 1,
    color1: "#ff5005",
    color2: "#dbba95",
    color3: "#d0bce1",
    envPreset: "city",
    grain: "on",
    lightType: "3d",
    positionX: -1.4,
    positionY: 0,
    positionZ: 0,
    range: "disabled",
    rangeEnd: 40,
    rangeStart: 0,
    reflection: 0.1,
    rotationX: 0,
    rotationY: 10,
    rotationZ: 50,
    shader: "defaults",
    uAmplitude: 1,
    uDensity: 1.3,
    uFrequency: 5.5,
    uSpeed: 0.4,
    uStrength: 4,
    uTime: 0,
    wireframe: false,
  },
];

/** Colours of the preset for phase `index` (cycled). */
export function phaseColors(index: number) {
  const p = presets[index % presets.length];
  return [p.color1, p.color2, p.color3] as string[];
}

/**
 * CSS stand-in for a phase's shader gradient: used for the cards behind the
 * active one, so only one WebGL context runs instead of one per card.
 */
export function phaseStill(index: number) {
  const [c1, c2, c3] = phaseColors(index);
  return `radial-gradient(120% 90% at 20% 15%, ${c2} 0%, transparent 60%), radial-gradient(100% 80% at 85% 90%, ${c3} 0%, transparent 65%), ${c1}`;
}
